seed: 1
work_dir: '.'
hydra:
    run:
        dir: ${work_dir}

# Environment Parameters

domain_name: hammer-v0
task_name: 
reward_type: dense
special_reset: 
cameras: [2]
action_repeat: 1

# RRL/CURL/RAD Training Parameters

agent: curl_sac
encoder_type: pixel
observation_type: pixel
pre_transform_image_size: 100
image_size: 84
frame_stack: 3
detach_encoder: False
data_augs: crop
latent_dim: 128
encoder_feature_dim: 50
encoder_lr: 1e-3
encoder_tau: 0.05
num_layers: 4
num_filters: 32

num_updates: 1
init_steps: 1000
num_train_steps: 1000000
batch_size: 32
hidden_dim: 1024
num_eval_episodes: 25

change_model: False
synch_update: False
two_conv: False
model_dir: 
model_step: 

# Warming up parameters

bc_only: False
warmup_cpc: 0
warmup_cpc_ema: False
warmup_offline_sac: 0

# Replay Buffer

replay_buffer_capacity: 100000
replay_buffer_load_dir: 

# Expert Demos

demo_samples: 25000
demo_model_step: 0
demo_model_dir: 
demo_special_reset: 
success_demo_only: False

# Sac params

discount: 0.99
init_temperature: 0.1
alpha_lr: 1e-4
alpha_beta: 0.5

# Actor Parameters

actor_lr: 1e-3
actor_beta: 0.9
actor_log_std_min: -10
actor_log_std_max: 2
actor_update_freq: 2

# Critic Parameters

critic_lr: 1e-3
critic_beta: 0.9
critic_tau: 0.01
critic_target_update_freq: 2

# Saving Flags & Logging

save_tb: False
save_buffer: False
save_video: True
save_model: True
save_sac: False

eval_freq: 5000
log_interval: 100
log_networks_freq: 1000000
